spring:
#  h2:
#    console:
#      enabled: true
  datasource:
#    url: jdbc:h2:mem:testdb
#  datasource:
    url: jdbc:mariadb://database-1.czosrniuxuqh.ap-northeast-2.rds.amazonaws.com:3306/knockknock
    username: eeheaven
    password: 122573aws
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 8081

logging:
  level:
    org.hibernate.sql: debug

